### ISSUE TITLE
Update use of auto prefix for environment variables

### ISSUE THREAD

**Issue by MichaelCurrin** [snth/numismatic#10]
The syntax for auto_envvar_variables is obscure to find but I eventually got it as `PREFIX_FUNCTION_VARIABLE` from [values-from-environment-variables](http://click.pocoo.org/5/options/#values-from-environment-variables)

e.g. the function "info"  with flag "--assets" expects a value like `$ export NUMISMATIC_INFO_ASSETS=ETH`

And you do have correct syntax in cli.py, if one wanted to use the auto prefix feature.
`coin(auto_envvar_prefix=ENVVAR_PREFIX)`

Unfortunately, the feature is restrictive in that it requires the _function_ name in the _middle_ i.e. NUMISMATIC_INFO_ASSETS, when we just want NUMISMATIC_ASSETS for use in info and prices.

Since it doen't work neatly for assets and currencies, then you could remove the feature, provided you don't need it for any other variables (where the function name is the middle is appropriate). That would be a single line code change to just have `coin()` at the end. And you can keep using your f-string style throughout as `envvar=f'{ENVVAR_PREFIX}_ASSETS'`, which is the most economical in this situation without  using the `auto_envvars_prefix` feature..

Let me know what you think.

**Comment by snth** [comment]
You're right. Let's do that!. Remove the `auto_envvars_prefix` and keep the rest.

**Comment by snth** [comment]
Fixed by #22
