### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by barrysteyn** [snth/numismatic#21]
How about this folder structure (this is just a suggestion, please alter):

 * numismatic
   * cli.py
   * lib
      * utils
      * requesters
      * events
   * datafeeds
      * base.py (this is the abc)
      * cryptocompare.py
      * luno.py
      * bravenewcoint.py
      *... etc
   * exchanges
      * base.py
      * luno.py <--- easy to see that luno is used both as a feed and as an exchange
      * bitfinex.py
      * ... etc

This is just a starting point for conversation...

**Comment by snth** [comment]
Looks good to me.

In your PR you named the `lib` directory, `libs`. Any thoughts on that? libs makes sense but I think lib is more common on posix systems.
